#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 5
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: COUNT_BASED
#      minimumNumberOfCalls: 5
#      waitDurationInOpenState: 10s
#      failureRateThreshold: 10
#    instances:
#      circuitBreakerName:
#        baseConfig: default



resilience4j.circuitbreaker:
  instances:
    circuitBreakerName:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 6




server:
  port: 9090